### ISSUE TITLE
The position of the facial model is very shaky

### ISSUE THREAD

**Issue by MolianWH** [keijiro/FaceLandmarkBarracuda#6]
Thanks for your help for making texture with face mesh in this [issue](https://github.com/keijiro/FaceMeshBarracuda/issues/15#issue-1268162663). I have successfully implemented it. But there also some problems with effectiveness.
1. How to make the face mesh look more closer with the real face. I tried set `transform.position = new Vector3(-0.5f, -0.5f, 0);` , but the position looks very shaky.
2. face mesh size looks not change with the distance of real face and camera. 
3. How to hidden the face mesh in scene when the mediaPipe not detect it?
4. Eyes mesh can not close.(I can use blendshape to implement it, but I want to drive mesh)
Bellow is the effect of  my implement. Could you give some ideas? Which code should I look at?Thanks.

https://user-images.githubusercontent.com/33748947/173726076-212c4c36-5193-4f26-ae5c-04cba5c1e48c.mp4

**Comment by keijiro** [comment]
The MediaPipe Face Mesh model only supports properly-cropped face image input. That's why it doesn't work and get shaky when your face is away from the camera. See the model card for details.

https://drive.google.com/file/d/1QvwWNfFoweGVjsXF3DXzcrCnz-mx-Lha/preview

Usually it needs integrating another face detector to crop input image properly. I used BlazeFace in the FaceMeshBarracuda project.

The answer above explains why 1., 2., 3. happen.

Regarding 4., the MediaPipe Face Mesh does nothing about eyes. You have to integrate another eye detection model. I used the MediaPipe Iris model in the FaceMeshBarracuda project.

**Comment by MolianWH** [comment]
Wow! Thanks for your quick response! That's very helpful！
